### ISSUE TITLE
scenario set-up TODO

### ISSUE THREAD

**Issue by n8thangreen** [n8thangreen/multimcm-simulationstudy#1]
- [ ] take average performance measure across all endpoints

- [x] pick scenarios, e.g. quantiles, rather than random sample of cure fractions, and rates

- [ ] can we use cauchy prior in sensitivity prior power R package?

- [ ] KM RMST equation
